version: "3"
services:
  strapi:
    image: naskio/strapi
    environment:
      NODE_ENV: development # oder production
    ports:
      - "1337:1337"
    volumes:
      - strapi-data:/srv/app/strapi-app
      
volumes:
  strapi-data: